### PR TITLE
chore(version): Version bump

### PR DESCRIPTION
**Pull request by asciidisco**

### CODE REVIEW

**Comment by emilsvennesson** [comment]
Thanks! Could you please also update changelog.txt and credit @gismo112 and yourself in the changelog?

**Comment by asciidisco** [comment]
@emilsvennesson Done.

**Comment by emilsvennesson** [comment]
@asciidisco Merged. Thanks a lot for helping out yet again! Feel free to submit this to the Kodi repo. :-)

**Comment by asciidisco** [comment]
@emilsvennesson I have absolutely no idea of the submission process. Any short pointers on what needs to be done here?

**Comment by emilsvennesson** [comment]
@asciidisco Sure thing! Fork the xbmc repo-scripts git and checkout the Krypton branch. Create a new branch and name the commit [script.module.inputstreamhelper] 0.2.2. They're really picky about only having one commit in the PR, so make sure to squash everything if you make multiple changes in the branch.

There's a good CONTRUBITING file available that I followed: https://github.com/xbmc/repo-scripts/blob/master/CONTRIBUTING.md

**Comment by asciidisco** [comment]
@emilsvennesson Thank you for the info. I will take care of the PR & mention you, so you can keep track.

**Comment by asciidisco** [comment]
Wasn't able to issue the PR to the repo-scripts repo earlier than today. But it already got merged, so, yeah \o/

**Comment by emilsvennesson** [comment]
@asciidisco Awesome! Thanks a lot.

**Pull request merged**
