### PR TITLE
Improve logging, file operations and Widevine CDM detection

### PR DESCRIPTION
**Pull request by mediaminister**
This pull request takes improvements from https://github.com/emilsvennesson/script.module.inputstreamhelper/pull/240 that are ready to be merged:
- allow logging on different levels
- wrap file operations in kodiutils.py
- rework Widevine CDM detection functionality
- various spelling and log messages corrections

### CODE REVIEW

**Comment by michaelarnauts** [comment]
Why do you use those magic constants with the log function? I very much prefer the real python logging interface where you can just use _LOGGER.debug() etc (like I did in viervijfzes), I'm clearly missing the point here :)

**Comment by mediaminister** [comment]
To make sure add-on reviewers don't notice that we are logging to a forbidden level. Silently breaking add-on rules to set a precedent.

**Comment by michaelarnauts** [comment]
Nice and honest :)

**Comment by horstle** [comment]
I think hardlink should rather be in utils instead of kodiutils. Other than that, looks good to me.

**Comment by mediaminister** [comment]
Okay, I moved the hardlink.

**Comment by dagwieers** [comment]
Thank, I will rebase #240

**Comment by dagwieers** [comment]
BTW I am not so fond of moving hardlink out of kodiutils as we want kodiutils to become a body of work that can be reused by other projects, and the hardlink functionality, while not related directly to kodi is something we think may be useful for other add-on projects as well. It is not inputstreamhelper specific.

But that said, we will fix this when kodiutils has become a separate module that is reused by different projects.

**Comment by mediaminister** [comment]
Okay.

**Comment by horstle** [comment]
Until now, kodiutils was a place to abstract kodi specific functions. hardlink is in no way related to kodi (neither directly nor indirectly). If I would search for a function creating hardlinks, with copy as fallback, I wouldn't look for it in a project called "kodiutils".

**Comment by michaelarnauts** [comment]
I agree with @horstle. IMO kodiutils should only contain functions for kodi. Another example is caching. These functions are useful, but don't belong in kodiutils.

**Comment by dagwieers** [comment]
@michaelarnauts That is a strange thing to say when we discussed moving routing in the future kodiutils project. Same for the proxy-handling code.

The general idea was to have one body of work to assist writing add-ons,. If we go and fragment kodiutils now between every add-on using it, there's no point in sharing one codebase.

Caching may be something different as this may be harder to abstract. It may be very close to how a VOD provider stores it metadata.

**Comment by mediaminister** [comment]
> The general idea was to have one body of work to assist writing add-ons.

Potayo, potahto. Can't we just name this future project `addonutils` and only group functions that are used by two or more add-ons?

**Comment by dagwieers** [comment]
@mediaminister That's the general idea. We postponed this for a few reasons:
- Once shared it will be hard to impossible to redesign an interface (so we need versioned libs, and/or synchronised releases)
- Some of the interfaces may benefit from a different interface (e.g. show_listing)
- For the stubs there may be conflicting use-cases (and maybe the stubs ought to go elsewhere anyway)

**Pull request merged**
