### PR TITLE
Support unicode chars in paths

### PR DESCRIPTION
**Pull request by mediaminister**
This fixes https://github.com/emilsvennesson/script.module.inputstreamhelper/issues/333

### CODE REVIEW

**Comment by horstle** [comment]
I think `mnt_path()` should return `to_unicode(mount_path)`, then it should actually fix the issue.

**Comment by horstle** [comment]
So the paths that I'd add to_unicode to are:
backup_path
mount_path
temp_path

**Comment by mediaminister** [comment]
I'll take another look at the other path functions, but the root cause is `xbmc.translatePath` in Kodi 18.x (Python 2.7) which needs a bytestring as input and returns a bytestring as output.

So, I ensured that the `translate_path` wrapper function does the necessary conversions in Python 2.7 with `to_unicode` and `from_unicode`.

**Comment by horstle** [comment]
Right, I forgot you added a test for a non-ascii temp_path already.
But `translate_path` already had a `to_unicode` before, so the output should already have been unicode, yet still `mount_path` is a bytestring.

**Comment by horstle** [comment]
Are you sure the output of `xbmc.translatePath` is a "normal" bytestring and not something kodi specific, which wouldn't be recognized by `isinstance(text, bytes)`?

**Comment by mediaminister** [comment]
> Are you sure the output of xbmc.translatePath is a "normal" bytestring
Yes, it's a bytestring in Kodi 18.x Python2

Testing unicode was unreliable because `unicode_literals` was imported in the tests. I'm trying to fix this now. Thinking how to mimic Kodi 18 and 19 behaviour with `addon_settings` in xbmcextra.py

**Pull request merged**
