### PR TITLE
Creates backup of CDM before installing new version and...

### PR DESCRIPTION
**Pull request by horstle**
...adds function to revert (is_helper.revert_cdm()). Maybe could be called by inputstream if there is an error?

### CODE REVIEW

**Comment by dagwieers** [comment]
I would like to take this one step further:
- Keep a number (say 5) backups of Widevine CDM versions
- Offer the option to install a Widevine CDM manually (so you can revert to any version)
- Show a selection of versions (based on versions.txt and what is on disk)

**Comment by horstle** [comment]
I could probably implement all that after #87 is done. Just not yet sure how to read the available versions in the settings page.

**Comment by dagwieers** [comment]
@horstle At this time I wouldn't spend too much time on it, we first need to get the basics right.

For me the absolute minimum is:
- Proper Widevine CDM version reporting (on ARM)
  - This requires we store both the ChromeOS image version as well as Widevine CDM version
- Interface to disable **inputstreamhelper**
- Interface to remove the currently used Widevine CDM library
- Interface to (re)install the Widevine CDM library

IMO we probably want to include the above as part of the upcoming release, given that it requires a minimum of effort and already covers 99% of the user's needs.

The need for backups and rolling back is only useful when we (ever) get a broken Widevine CDM. And we should be looking at #69 to make this case more user-friendly first. Otherwise you will be needing to rebase and resolve conflicts all the time :-/

**Comment by dagwieers** [comment]
I opened a new feature request for this #165 with some more details.

**Comment by dagwieers** [comment]
This relates to #165. I don't mind keeping this one open in case @horstle wants to reuse this branch for this work ;-)

**Comment by horstle** [comment]
Closing this in favor of #193.

**Pull request closed without merging**
