### PR TITLE
Add options to run manually and force a reinstall via the settings page.

### PR DESCRIPTION
**Pull request by horstle**
Hi,

I did not test this yet, but since it was requested multiple times (#47 and #32) I thought I'd create this draft PR so others could have a look at it/ test it.

### CODE REVIEW

**Comment by horstle** [comment]
Just tested on Windows and found an issue when module is disabled. Should be fixed now.

**Comment by dagwieers** [comment]
I would like to add this, together with #34 

Can you rebase this PR ?

**Comment by horstle** [comment]
Done.

**Comment by dagwieers** [comment]
We added sanity checks, and I know it is a nuisance for existing PRs, sorry for that.
I hope you don't mind fixing those, and let us know if you are stuck with any.

**Comment by horstle** [comment]
I know, I had seen those and fixed most of them in the last commit, except the protected-access, since I'm not sure what to do about it. Should I make _widevine_config_path "unprotected"? I don't know how else this could be resolved.

**Comment by horstle** [comment]
Another rebase, another string ID changed...
Any answer to my last comment?

**Comment by dagwieers** [comment]
@horstle Yes, you may need to make it "unprotected". However, rather than a script I would prefer we have a plugin API. Although I am not sure if that is possible for a **script.module** plugin.

**Comment by horstle** [comment]
Alright, closing this since there is a more elegant solution now. #91

**Pull request closed without merging**
