### PR TITLE
v0.4.4 release

### PR DESCRIPTION
**Pull request by mediaminister**
Preparing for the v0.4.4 release:

- updated README
- updated addon.xml
- remove newline in German strings.po

### CODE REVIEW

**Comment by dagwieers** [comment]
# [Codecov](https://codecov.io/gh/emilsvennesson/script.module.inputstreamhelper/pull/257?src=pr&el=h1) Report
> Merging [#257](https://codecov.io/gh/emilsvennesson/script.module.inputstreamhelper/pull/257?src=pr&el=desc) into [master](https://codecov.io/gh/emilsvennesson/script.module.inputstreamhelper/commit/1ace2ef1aa6386c3bc25d4f90aac3033458bf608&el=desc) will **increase** coverage by `0.63%`.
> The diff coverage is `n/a`.

[Impacted file tree graph](https://codecov.io/gh/emilsvennesson/script.module.inputstreamhelper/pull/257?src=pr&el=tree)

```diff
@@            Coverage Diff             @@
##           master     #257      +/-   ##
==========================================
+ Coverage   76.87%   77.51%   +0.63%     
==========================================
  Files          18       18              
  Lines        1769     1819      +50     
==========================================
+ Hits         1360     1410      +50     
  Misses        409      409              
```


| [Impacted Files](https://codecov.io/gh/emilsvennesson/script.module.inputstreamhelper/pull/257?src=pr&el=tree) | Coverage Δ | |
|---|---|---|
| [test/xbmc.py](https://codecov.io/gh/emilsvennesson/script.module.inputstreamhelper/pull/257/diff?src=pr&el=tree#diff-dGVzdC94Ym1jLnB5) | `59.28% <0.00%> (+0.24%)` | :arrow_up: |
| [lib/inputstreamhelper/\_\_init\_\_.py](https://codecov.io/gh/emilsvennesson/script.module.inputstreamhelper/pull/257/diff?src=pr&el=tree#diff-bGliL2lucHV0c3RyZWFtaGVscGVyL19faW5pdF9fLnB5) | `78.17% <0.00%> (+0.48%)` | :arrow_up: |
| [test/xbmcaddon.py](https://codecov.io/gh/emilsvennesson/script.module.inputstreamhelper/pull/257/diff?src=pr&el=tree#diff-dGVzdC94Ym1jYWRkb24ucHk=) | `85.71% <0.00%> (+0.71%)` | :arrow_up: |
| [test/test\_api.py](https://codecov.io/gh/emilsvennesson/script.module.inputstreamhelper/pull/257/diff?src=pr&el=tree#diff-dGVzdC90ZXN0X2FwaS5weQ==) | `93.75% <0.00%> (+1.15%)` | :arrow_up: |
| [test/xbmcgui.py](https://codecov.io/gh/emilsvennesson/script.module.inputstreamhelper/pull/257/diff?src=pr&el=tree#diff-dGVzdC94Ym1jZ3VpLnB5) | `77.51% <0.00%> (+3.90%)` | :arrow_up: |

------

[Continue to review full report at Codecov](https://codecov.io/gh/emilsvennesson/script.module.inputstreamhelper/pull/257?src=pr&el=continue).
> **Legend** - [Click here to learn more](https://docs.codecov.io/docs/codecov-delta)
> `Δ = absolute <relative> (impact)`, `ø = not affected`, `? = missing data`
> Powered by [Codecov](https://codecov.io/gh/emilsvennesson/script.module.inputstreamhelper/pull/257?src=pr&el=footer). Last update [1ace2ef...69db4e4](https://codecov.io/gh/emilsvennesson/script.module.inputstreamhelper/pull/257?src=pr&el=lastupdated). Read the [comment docs](https://docs.codecov.io/docs/pull-request-comments).

**Comment by CastagnaIT** [comment]
if possible i would like to know a provisional release date for this release

**Comment by dagwieers** [comment]
@CastagnaIT Is there a particular reason you need this? Any specific functionality you need?

**Comment by CastagnaIT** [comment]
You remember the problem with the wrong return value of
check_inputstream()
which has now been fixed?

For the next release i implemented at startup of the addon an auto-configuration of the addon, but i used the check_inputstream() (it's better and it simplifies a lot of things)

so with the current version of inputstreamhelper, the addon auto-configuration will be ineffective, due to the wrong returned value, then i will have to wait this version

**Comment by horstle** [comment]
In the future, it might be a good idea, to use different branches for different releases, so e.g. backup and rollback support could have been merged into an v0.5 branch, while bugfixes would of course be in both v0.4 and v0.5. That would have made it easier to release v0.4.4 with bugfixes only, which wouldn't need that much testing and no new translations.

**Comment by dagwieers** [comment]
We can still do that by cherry-picking it to a temporary v0.4.5 branch, but I don't think this is the reason for the current delays. I guess we did not see any resolved issues as being critical in the proper working of the add-on wrt. impact and scope. Or at least nobody reported this as being a reason for doing another release with some urgency.

**Comment by mediaminister** [comment]
I can release what we have this weekend.

**Comment by CastagnaIT** [comment]
thank you very much

**Comment by dagwieers** [comment]
# [Codecov](https://codecov.io/gh/emilsvennesson/script.module.inputstreamhelper/pull/257?src=pr&el=h1) Report
> Merging [#257](https://codecov.io/gh/emilsvennesson/script.module.inputstreamhelper/pull/257?src=pr&el=desc) into [master](https://codecov.io/gh/emilsvennesson/script.module.inputstreamhelper/commit/72830e80a77b40d31ebc57dabe993a14106c3951&el=desc) will **decrease** coverage by `0.81%`.
> The diff coverage is `n/a`.

[Impacted file tree graph](https://codecov.io/gh/emilsvennesson/script.module.inputstreamhelper/pull/257?src=pr&el=tree)

```diff
@@            Coverage Diff             @@
##           master     #257      +/-   ##
==========================================
- Coverage   78.12%   77.31%   -0.82%     
==========================================
  Files          18       18              
  Lines        1838     1838              
==========================================
- Hits         1436     1421      -15     
- Misses        402      417      +15     
```


| [Impacted Files](https://codecov.io/gh/emilsvennesson/script.module.inputstreamhelper/pull/257?src=pr&el=tree) | Coverage Δ | |
|---|---|---|
| [lib/inputstreamhelper/utils.py](https://codecov.io/gh/emilsvennesson/script.module.inputstreamhelper/pull/257/diff?src=pr&el=tree#diff-bGliL2lucHV0c3RyZWFtaGVscGVyL3V0aWxzLnB5) | `90.90% <0.00%> (-9.10%)` | :arrow_down: |
| [lib/inputstreamhelper/\_\_init\_\_.py](https://codecov.io/gh/emilsvennesson/script.module.inputstreamhelper/pull/257/diff?src=pr&el=tree#diff-bGliL2lucHV0c3RyZWFtaGVscGVyL19faW5pdF9fLnB5) | `76.39% <0.00%> (-1.74%)` | :arrow_down: |

------

[Continue to review full report at Codecov](https://codecov.io/gh/emilsvennesson/script.module.inputstreamhelper/pull/257?src=pr&el=continue).
> **Legend** - [Click here to learn more](https://docs.codecov.io/docs/codecov-delta)
> `Δ = absolute <relative> (impact)`, `ø = not affected`, `? = missing data`
> Powered by [Codecov](https://codecov.io/gh/emilsvennesson/script.module.inputstreamhelper/pull/257?src=pr&el=footer). Last update [72830e8...8d080d8](https://codecov.io/gh/emilsvennesson/script.module.inputstreamhelper/pull/257?src=pr&el=lastupdated). Read the [comment docs](https://docs.codecov.io/docs/pull-request-comments).

**Comment by dagwieers** [comment]
I only have 4G network this weekend, so testing ARM will not be possible. I will fix codecov and call out to translators later this evening, if it hasn't been done already.

Will the next release be v0.4.4 or v0.5.0 ?

**Comment by mediaminister** [comment]
@dagwieers Translations are complete (https://github.com/emilsvennesson/script.module.inputstreamhelper/issues/256), except Japanese and Korean, but I won't wait for that.
I will release v0.4.4 in one hour because we are blocking a new release of the Netflix add-on, I tested today and I don't expect problems with x86.

**Pull request merged**
