### PR TITLE
check widevine support before all checks

### PR DESCRIPTION
**Pull request by vlmaksime**

### CODE REVIEW

**Comment by dagwieers** [comment]
Can you please rebase your branch?

**Comment by dagwieers** [comment]
Also, I am not sure if this change is even relevant, as the add-on should be using:
```python
    is_helper = inputstreamhelper.Helper(PROTOCOL, drm=DRM)
    if is_helper.check_inputstream():
```
in order to check if **inputstreamhelper** is needed. So the only potential improvement is making a quicker decision based on other criteria.

**Comment by dagwieers** [comment]
This is weird, the resulting file looks fine, but the diff includes the proxy support?
Seems like a GitHub bug?

**Comment by vlmaksime** [comment]
Now it looks correct

**Comment by dagwieers** [comment]
How about https://github.com/emilsvennesson/script.module.inputstreamhelper/pull/30#issuecomment-522544889 ?

**Comment by mediaminister** [comment]
`drm` is an optional argument, so this could also be `None`, so I think checking the value of `drm` makes sense.

**Comment by dagwieers** [comment]
With the power vested in me, I'll merge :-D

**Pull request merged**
