### PR TITLE
Support vendor widevine library (reworked)

### LINKED ISSUE #229: Support vendor distributed Widevine
Hi,

I reached out to @dagwieers initially via email as this isn't an issue per se. 

It would be good to start a discussion about how to handle vendor distributed versions of Widevine. We (OSMC) would like to distribute our own version of Widevine. We have satisfied the legal requirements to distribute these libraries directly for some supported platforms. 

Understandably, this add-on is brought in as a dependency by a number of add-ons that utilise Widevine. I'd suggested a symlink (such as /usr/lib/libwidevine-cdm.so -> /usr/lib/libwidevine-vendor.so to signal recognition), but @dagwieers has mentioned quite correctly that this wouldn't be suitable for Windows.

In short, it would be good to adapt this add-on so it can detect a vendor provided version of Widevine and devolve updates to the distribution. 

Cheers

Sam

### PR DESCRIPTION
**Pull request by dagwieers**
This adds support for a vendor-supported Widevine library.

**TODO:**
- ~Get timestamp from library to show in info pane~
- Disable settings/operations

This is PR #240 reworked and fixes #229

### CODE REVIEW

**Comment by dagwieers** [comment]
The information pane will look like this:
> **Kodi information**
> - Kodi version: **18.6**
> - Kodi platform/architecture: **Linux/arm**
>
> **InputStream information**
> - InputStream Helper version: **0.4.5**
> - InputStream Adaptive version: **2.4.4**
>
> **Widevine information**
>- Widevine version: **4.10.1440.18 (supplied by vendor)**
>
> Please report issues to:
> - https://github.com/emilsvennesson/script.module.inputstreamhelper/issues

**Comment by dagwieers** [comment]
@samnazarko Is there any progress from your side on this? Have you tested this implementation?

**Comment by samnazarko** [comment]
I’ll check this shortly

Sam

On 14 Apr 2020, at 17:24, Dag Wieers <notifications@github.com> wrote:

﻿

@samnazarko<https://github.com/samnazarko> Is there any progress from your side on this? Have you tested this implementation?

**Comment by samnazarko** [comment]
It's not clear to me where my libwidevinecdm_vendor.so should go. I can only see references to it in the unit tests and couldn't see any other code that references it elsewhere.

Cheers,

Sam

**Comment by dagwieers** [comment]
@samnazarko AFAIK It is in the same location as where it currently lives, but with a vendor-label added. On a Linux system it would be in ~/.kodi/cdm/

**Comment by samnazarko** [comment]
OK, I'll give this a test tomorrow.

Thanks Dag

Sam

**Comment by samnazarko** [comment]
Hi Dag - just to let you know, this isn't forgotten. I'm currently having to port over Widevine15 changes which is proving tricky.

**Comment by dagwieers** [comment]
@samnazarko We have started working on the upcoming v0.5.0 release which greatly improves extracting the Widevine CDM for ARM devices. It would be nice if this could ship with v0.5.0.

**Comment by samnazarko** [comment]
We have made some progress on porting Widevine 15 and passing user acceptance testing.

I should be able to check this again next week.

On 5 May 2020, at 17:06, Dag Wieers <notifications@github.com> wrote:

﻿

@samnazarko<https://github.com/samnazarko> We have started working on the upcoming v0.5.0 release which greatly improves extracting the Widevine CDM for ARM devices. It would be nice if this could ship with v0.5.0.

**Comment by samnazarko** [comment]
Hi @dagwieers  -- sorry for the late reply and to keep you waiting.

I think you can get this merged. The new Widevine changes mean that we may not be able to use InputStream directly, but it can at least display the correct information about the present Widevine library.

**Comment by dagwieers** [comment]
@samnazarko Thanks for the feedback.

@mediaminister @horstle Is there something we want to add to this?

**Comment by mediaminister** [comment]
No, I would like to know how this can be tested.

**Comment by horstle** [comment]
The install/remove options from the settings page might create issues?

**Comment by dagwieers** [comment]
All good points. Since this PR is again obsoleted by recent changes I am going to close it.
Feel free to pursue this if you have a need for this.

**Comment by horstle** [comment]
I'll have a look at it in the next few days, but it almost certainly won't be ready for v0.5.0, which imo should be released this weekend, even if some translations might still be missing.

**Pull request closed without merging**
