### PR TITLE
Access the zipped Chrome OS image directly

### LINKED ISSUE #72: Access the zipped image directly to extract CDM
There are four major issues with inputstreamhelper on ARM:
- The need for root privileges in order to mount the disk image
- The required tools and kernel capability for performing the process
- The need for 2GB of free disk space
- The time to uncompress a 600MB image on a RPi and write 2GB to an SD card

We can avoid all of this, by using FUSE to mount as a user, and using zipfs to mount the zipped image directly without the need to extract the complete image.

There is a fusepy project to create python-based fuse modules, and there is a zipfs fuse module written in python as well. Currently this enables us to access the binary without the need to uncompress the ZIP file, but it does not allow us to mount the filesystem from without this mounted ZIP file. So what we need to do is create our own extzipfs that does both in a single mount. Or alternatively, instead of mounting it, use the fuse interface to get that file directly from the zipped ext2 image.

This would save us a great deal of time as well, as we wouldn't have to write to the SD card as heavily as we do now.

### PR DESCRIPTION
**Pull request by horstle**
Okay, as promised in https://github.com/emilsvennesson/script.module.inputstreamhelper/pull/319#issuecomment-623191660, here is another PR about installing Widevine on ARM.

It accesses the zipped image directly, and extracts the lib from it. On an RPi3 this takes around half the time it takes to extract the whole image and (obviously) only uses about one third of disk space.

I tested this on an RPi3 and it seems to work. The reason it's still a Draft PR is because the progress dialog needs improvement and there are some messages not yet localized (mainly in the progress dialog).
But you're welcome to test it already, the only changes I have planned are the two points mentioned above and they shouldn't affect the actual code.

This is based on #327 and (imho) supersedes #319 . It resolves #72 .

### CODE REVIEW

**Comment by dagwieers** [comment]
I wanted to fix the checks, but I have no permission on your branch.
```diff
diff --git .pylintrc .pylintrc
index 89bedcf..1a60cdd 100644
--- .pylintrc
+++ .pylintrc
@@ -1,9 +1,10 @@
 [MESSAGES CONTROL]
 disable=
     bad-option-value,
-    duplicate-code,
-    import-outside-toplevel,
-    line-too-long,
+    duplicate-code,  # Integration tests tend to test similar things
+    fixme,  # Allow FIXMEs in code is a useful practice
+    import-outside-toplevel,  # Done on purpose to reduce overhead at startup
+    line-too-long,  # Flake8 is used for testing line-length
     old-style-class,
     too-many-arguments,
     too-many-branches,
diff --git lib/inputstreamhelper/widevine/arm.py lib/inputstreamhelper/widevine/arm.py
index 45048cf..a973d1a 100644
--- lib/inputstreamhelper/widevine/arm.py
+++ lib/inputstreamhelper/widevine/arm.py
@@ -190,7 +190,7 @@ def install_widevine_arm(backup_path):
     return False
 
 
-def install_wv_arm_legacy(backup_path):  # pylint: disable=too-many-statements
+def install_wv_arm_legacy(backup_path):
     """Legacy method to install Widevine CDM on ARM-based architectures."""
     root_cmds = ['mount', 'umount', 'losetup', 'modprobe']
     devices = chromeos_config()
```
I think it is convenient/practical to fix small issues like this directly, rather than have to point them out and have someone else fix them.

**Comment by dagwieers** [comment]
This is looking really good. I tested it briefly and I have only 2 additional minor items:
- The download progress dialog is nice, however I would probably only update remaining time every 5 seconds, but I would add a download rate (e.g. 568 kB/sec) which does update every second (so we have changes in the dialog, and it will show 0 kB/sec when the download stalls)
- What I find disturbing visually is that the download of the license is only briefly showing a progress dialog. IMO that dialog is useless as the download usually will only take a few seconds (in my case it seems sub-second). If the plan is online streaming, we can expect people to have a big pipe anyway.

Thanks for this! I spend quite some time looking at implementing something like this, but based on existing libraries/tools. If I have one concern, then it is that it may be more prone to changes to the image. The upside is that if such changes are coming, we can easily fix those (whereas with the old implementation that would be much harder to come by).

We hope that with the Google LaCrOS plans an easier ARM download (and who knows ARM64) will become available. I frequently test for new widevine ZIP files but have not detected any yet.

**Comment by horstle** [comment]
> I think it is convenient/practical to fix small issues like this directly, rather than have to point them out and have someone else fix them.

I'm currently working on and force-pushing to that branch, so I might have accidentally overwritten your changes, but I'll give you write access soon. I added your changes now.

>     * The download progress dialog is nice, however I would probably only update remaining time every 5 seconds or delay showing the ETA with 10 seconds (given the great variance, especially at the start), but I would add a download rate (e.g. 568 kB/sec) so we have changes in the dialog, and it will show download stalls (i.e. 0 kB/sec)
> 
>     * What I find disturbing visually is that the download of the license is only briefly showing a progress dialog. IMO that dialog is useless as the download usually will only take a few seconds (in my case it seems sub-second). If the plan is online streaming, we can expect people to have a big pipe anyway.

There is definitely room for improvement here, however that's not related to this PR (this was changed in #339 ), so I think this should get it's own issue.

> Thanks for this! I spend quite some time looking at implementing something like this, but based on existing libraries/tools. If I have one concern, then it is that it may be more prone to changes to the image. The upside is that if such changes are coming, we can easily fix those (whereas with the old implementation that would be much harder to come by).

Do you have any specific change in mind, which would break this? The filesystem changing or the partition name not being 'ROOT-A' anymore are changes that I thought of, but I think they are rather improbable (for now, might change once ARM64 is there).

**Comment by horstle** [comment]
Alright, I think it's ready now. On an RPi3 the progress dialog might stay the same for a few seconds, but IMO that's not too long, even if it was longer on slower hardware.

**Comment by dagwieers** [comment]
> Do you have any specific change in mind, which would break this? The filesystem changing or the partition name not being 'ROOT-A' anymore are changes that I thought of, but I think they are rather improbable (for now, might change once ARM64 is there).

I think we make the following assumptions:
- GPT is used
- Partition name is `ROOT-A`
- Filesystem is ext2

But as I said, this is no worse than we had before. In fact, it will be easier to fix in our code than having tools no longer being able to cope with the changes.

I think we need another change I will propose for #344 which is that we also store the platform name (image) used. If we get reports it might be because of a broken/incompatible ZIP image and if this would be a temporary situation, we cannot easily reproduce without this information.

Same for a broken Widevine, it would be nice to find where it was coming from.

**Comment by dagwieers** [comment]
I would still update the progress dialog with more meaningful messages. "Reading the file..." does not bring anything to the table. We might as well keep saying "Extracing Widevine CDM...".

I think we can give a bit more insightful message, like:
- Opening compressed ChromeOS image...
- Identifying partition...
- Reading file system...
- Scanning the file system for Widevine CDM...
- Widevine CDM found, extracting to disk...

For every stage where we may expect trouble in the future it could be useful to update the message so that the user can report "When it failed, the progress bar showed: ...". While we prefer a full log, it helps if the user can easily relate their issue with existing open issues.

**Comment by dagwieers** [comment]
Let's merge this, and improve whatever needs improving. I guess this is the start of the v0.5.0 development cycle. Welcome, and thanks @horstle !

**Comment by dagwieers** [comment]
Wrt. potential future changes to the ChromeOS images, what we could do is run our unit tests for ARM in a **Status** GitHub workflow e.g. every 2 hours just to make sure we have an advance notice when it starts failing. (Even better would be to only test when a new selected image was released...)

**Pull request merged**
