### PR TITLE
Add Widevine support for ARM64 Mac

### PR DESCRIPTION
**Pull request by mediaminister**
This adds Widevine support for Mac computers with ARM64 architecture (Apple M1)

Please test, I don't own Apple hardware myself.

### CODE REVIEW

**Comment by CastagnaIT** [comment]
i think also apple tv is arm64 right or wrong?

**Comment by mediaminister** [comment]
Yes, Apple TV HD en 4K is definitely ARM64.

**Comment by tmm1** [comment]
@mediaminister do you mind fixing the conflicts, I can test it on M1

**Comment by mediaminister** [comment]
@tmm1 Done, wondering is this works on M1

**Comment by tmm1** [comment]
@mediaminister Confirmed working as expected. Downloads the mac-arm64 cdm and then ISA is able to play DASH/WV correctly.

**Comment by horstle** [comment]
Thanks @tmm1 for testing. Going to merge this now.

**Pull request merged**
