### PR TITLE
Fixes #5

### LINKED ISSUE #5: [Windows 64bit] - Wrong widevine lib (for 32bit systems) will be fetched
Using `arch = platform.machine()` to determine the Windows system type doesn't seem to be sufficient for 64bit systems, as the return value is `AMD64` regardless of the architecture.

This can be solved by utilizing `platform.architecture()` to fetch the system architecture (and it wouldn't do any harm if done so).

### PR DESCRIPTION
**Pull request by gismo112**

### CODE REVIEW

**Comment by emilsvennesson** [comment]
Hi and thank you for the PR!

I'm currently abroad with no access to anything but my phone for 6+ weeks so testing anything right now is kind of difficult to me.

@asciidisco Does this seem like a good solution to you? I am going to go ahead and merge it if you give me the OK. :-)

**Comment by emilsvennesson** [comment]
I actually have one question myself now that I think about it: are you sure that using the x64 library on Windows is working? If I recall correctly, I never got that to work while using 32-bit on 64-bit Windows worked just fine.

**Comment by gismo112** [comment]
The 32bit widevinecdm works fine on Windows x64 System, when a Kodi 32-bit Build in use.
When you use a Kodi 64-bit Build (with comes on kodi 18 Leia) u need the 64bit widevinecdm.
On all Windows 64bit Systems the answer for `platform.machine()` is `AMD64`,
no matter which Kodi-Version(x86 or x64) is used in Windows.
I hope, i can you help a little bit :-)

**Comment by emilsvennesson** [comment]
Ah right, I had forgotten about the 64-bit Kodi builds! Have you verified that the 64-bit Widevine CDM works on 32-bit Kodi builds as well? This PR would break compatibility the other way otherwise if I'm not mistaken.

**Comment by emilsvennesson** [comment]
Or does platform.architecture() detect if you're running a 64 or 32-bit Kodi build? It all makes sense to me then, haha... Again, it's hard reviewing PR:s on a phone!

**Comment by gismo112** [comment]
The 64-bit Widevinecdm don´t work on a Kodi 32bit. 
Yes, the platform.architecture() detect if you use a 32bit or a 64bit Kodi.
No Problem, i help so i can. @asciidisco help me, because my written English is not the best :-)

**Comment by emilsvennesson** [comment]
Ah right, I got it now. No need to excuse about your English, it's more than fine. :-) I just confused myself a bit I think, haha!

I'll wait for @asciidisco to give his input but this looks good to me. Thanks again for the PR!

**Comment by asciidisco** [comment]
@emilsvennesson @gismo112 Just found the time to test it in my VM setup. Worked for me :)
Is there anything I can be of assistance in regards to version bumps, and/or getting the new version into the Kodi repo?

**Comment by emilsvennesson** [comment]
Merged. Thanks a lot @gismo112 and @asciidisco!

@asciidisco Yes, I'd appreciate a lot if you could PR a 0.2.2 version bump. I can merge and tag it from my phone and then I'd be completely fine with you submitting it to the Kodi repo. Thanks a lot for helping out! :-)

**Comment by asciidisco** [comment]
@emilsvennesson Will do this evening. And no worries, I‘m the one who has to thank you as I hopefully will need to give less support regarding Widevine issues in the future.
Also, I‘ve been very glad that it got merged into the main Repo :)

**Comment by gismo112** [comment]
@emilsvennesson @asciidisco 
When one help each other, we all have a less problems :) Special Thanks @asciidisco for your help and testing :)

**Comment by asciidisco** [comment]
PR is up

**Pull request merged**
