### PR TITLE
Improves info dialog

### PR DESCRIPTION
**Pull request by horstle**
I modified the info dialog, as @dagwieers suggested in https://github.com/emilsvennesson/script.module.inputstreamhelper/issues/344#issuecomment-635894710, except for some tiny changes to the wording.
This changes every line related to info dialog in strings.po. I'll udpate the other languages before merging, but I wanted to get you opinions first. Should the wording be changed somewhere? Or should the dialog be changed at all?

### CODE REVIEW

**Comment by horstle** [comment]
I updated the language files now.

**Comment by dagwieers** [comment]
@horstle This is great, I made one change and translated it to Dutch as well. Currently (and in my proposal) "Widevine CDM" was repeated, but IMO it reads better if the next lines refer to the first in that paragraph.

Now it looks like this:
> **Kodi** version **18.6** is running on a **Linux** system with **arm** architecture.
>
> **InputStream Helper** is at version **0.4.7**
> **InputStream Adaptive** is at version **2.4.5.1**
>
> **Widevine CDM** is at version **4.10.1610.6** and was installed on **Never**
> It was extracted from Chrome OS image **JAQ** with version **12871.102.0**
> It was last checked for updates on **Never**
> It is installed at **/storage/.kodi/cdm**
>
> Please report issues to: *https://git.io/JfKJb*

I also highlighted **InputStream Helper** and **InputStream Adaptive**.

**Comment by dagwieers** [comment]
Sidenote: With all the recent changes, I think we are ready to prepare for a v0.5.0 release, or maybe finally a v1.0.0 release. We could ask to get everything translated as widely as possible (again). Unless we expect to add/change some more text strings for this release.

**Comment by mediaminister** [comment]
> Sidenote: With all the recent changes, I think we are ready to prepare for a v0.5.0 release, or maybe finally a v1.0.0 release.

Let's keep it v0.5.0 if https://github.com/emilsvennesson/script.module.inputstreamhelper/pull/311 isn't ready yet.

**Comment by horstle** [comment]
I like the changes made by @dagwieers . I'll merge this now.

If #311 won't be in v0.5.0, I think we could ask for translations, else we should wait for that, since it adds another string.

**Pull request merged**
