### PR TITLE
fix python3 compatibility

### PR DESCRIPTION
**Pull request by Rechi**
This is compatible with python3 and python 2.7 (krypton and leia).

### CODE REVIEW

**Comment by Rechi** [comment]
@emilsvennesson ping

**Comment by emilsvennesson** [comment]
@Rechi Is this all that's needed for python 3 compability? I'm currently on vacation with no access to a computer until the beginning of January.

**Comment by Rechi** [comment]
> I'm currently on vacation with no access to a computer

Didn't know that and just wanted to make sure you haven't missed / forgotten this PR. There is no rush to get this PR merged.
\
\
I don't know if it is the only thing needed for complete python 3 compatibility, I tested the following
- installed YouTube, opening root view and playing videos works
- enabled 'Use MPEG-DASH', opening YouTube root view and playing videos works
- selected 'Install InputStream Helper', opening YouTube root view **fails**
- adjusted the code, opening YouTube root view and playing videos works again
\
\
This is the exception I got without the modified code.
```
EXCEPTION Thrown (PythonToCppException) :
-->Python callback/script returned the following error<--
 - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
Error Type: <class 'SyntaxError'>
Error Contents: invalid token (inputstreamhelper.py, line 616)
Traceback (most recent call last):
  File "[...]\addons\plugin.video.youtube\resources\lib\default.py", line 4, in <module>
    from youtube_plugin import youtube
  File "[...]\addons\plugin.video.youtube\resources\lib\youtube_plugin\youtube\__init__.py", line 5, in <module>
    from .provider import Provider
  File "[...]\addons\plugin.video.youtube\resources\lib\youtube_plugin\youtube\provider.py", line 10, in <module>
    from ..youtube.helper import yt_subscriptions
  File "[...]\addons\plugin.video.youtube\resources\lib\youtube_plugin\youtube\helper\__init__.py", line 5, in <module>
    from .url_to_item_converter import UrlToItemConverter
  File "[...]\addons\plugin.video.youtube\resources\lib\youtube_plugin\youtube\helper\url_to_item_converter.py", line 7, in <module>
    from . import utils
  File "[...]\addons\plugin.video.youtube\resources\lib\youtube_plugin\youtube\helper\utils.py", line 12, in <module>
    import inputstreamhelper
  File "[...]\addons\script.module.inputstreamhelper\lib\inputstreamhelper.py", line 616
    os.chmod(self._widevine_path(), 0744)  # this needs to be octal in python 3
                                       ^
SyntaxError: invalid token
-->End of Python script error report<--
```

**Comment by emilsvennesson** [comment]
@Rechi Thank you! I will continue working on this module once I am back home.

**Comment by goggle** [comment]
@emilsvennesson Is a release of `script.module.inputstreamhelper` which contains this change in the Krypton repository yet? That would be necessary for my SRG SSR plugins to work with Python 3. If not, would it be possible to release a new version of `script.module.inputstreamhelper` that contains this commit? Thanks.

**Comment by emilsvennesson** [comment]
@goggle It's not, because I have not yet been able to test if there's anything else that needs to be done for Python 3 compabilty. I will continue the development on the module next month.

Sorry for the delay.

**Comment by horstle** [comment]
I'm pretty sure the
```python
import config
```
line needs to be changed, since implicit imports aren't allowed in python3. maybe try running [2to3](https://docs.python.org/2/library/2to3.html) on it.

**Comment by mediaminister** [comment]
I made a pull request with only three small changes that fixed python 2_3 support for this script module. I tested this on the Kodi Python3 test-build for Windows 10 x64 and it works.

**Comment by horstle** [comment]
@mediaminister
Please see #42 , why these changes won't work in all cases.

**Comment by mediaminister** [comment]
@horstle: You're right. But `.decode('utf-8')` doesn't exist in Python 3. Do you have any idea how `xbmc.translatePath(ADDON.getAddonInfo('profile'))` can be ever made compatible with python 2 and python 3?

**Comment by horstle** [comment]
Not right now. I might have a look at it next weekend. I wanted to work on this anyway along with an option to run the helper manually and removing the DialogBusy stuff (deprecated in Kodi 18).

**Comment by Rechi** [comment]
You could use https://github.com/romanvm/kodi.six.

**Pull request merged**
