### PR TITLE
Add platform integration tests

### LINKED ISSUE #116: Unicode issue on Python 3
Integration tests of the ARM installation procedure on Python 3 revealed another unicode issue:
```traceback
======================================================================
ERROR: test_check_inputstream_mpd_again (test.test_ishelper_lin_arm.LinuxARMTests)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/travis/build/emilsvennesson/script.module.inputstreamhelper/test/test_ishelper_lin_arm.py", line 28, in test_check_inputstream_mpd_again
    is_installed = is_helper.check_inputstream()
  File "/home/travis/build/emilsvennesson/script.module.inputstreamhelper/lib/inputstreamhelper.py", line 947, in check_inputstream
    return self._check_drm()
  File "/home/travis/build/emilsvennesson/script.module.inputstreamhelper/lib/inputstreamhelper.py", line 901, in _check_drm
    return self.install_widevine()
  File "/home/travis/build/emilsvennesson/script.module.inputstreamhelper/lib/inputstreamhelper.py", line 686, in install_widevine
    return self._install_widevine_arm()
  File "/home/travis/build/emilsvennesson/script.module.inputstreamhelper/lib/inputstreamhelper.py", line 613, in _install_widevine_arm
    localize(30006, diskspace=self._sizeof_fmt(required_diskspace))) and self._widevine_eula():
  File "/home/travis/build/emilsvennesson/script.module.inputstreamhelper/lib/inputstreamhelper.py", line 763, in _widevine_eula
    eula = f.read().strip().replace('\n', ' ')
TypeError: a bytes-like object is required, not 'str'
```

### PR DESCRIPTION
**Pull request by dagwieers**
This performs integrations tests for:
- Linux x86_64
- Linux ARM
- Windows x86_64
- Darwin x86_64

This fixes #116

### CODE REVIEW

**Comment by dagwieers** [comment]
This includes two Python 3 issues, and disables printing HTTP response (as this is quite large in the case of recovery.conf).

**Comment by mediaminister** [comment]
Unit tests for ARM are still failing on my system. I suspect I just don't have enough free disk space.
But I always get a very short traceback:
```
FAIL: test_check_inputstream_mpd_again (test.test_ishelper_lin_arm.LinuxARMTests)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/test/script.module.inputstreamhelper/test/test_ishelper_lin_arm.py", line 29, in test_check_inputstream_mpd_again
    self.assertTrue(is_installed, True)
AssertionError: True
```
Is there an option to get a longer traceback?

**Comment by dagwieers** [comment]
@mediaminister You have to scroll up to identify which *method* failed and look at the cause there. I don't like how this was designed either ;-) But it runs all tests, even if some fail, and only the assertion is displayed.

I have an issue with the ARMTests on my system too, and it is related to:
```log
Debug: [script.module.inputstreamhelper-1.2.3]: Failed to calculate losetup offset.
```

My interpretation is that this was designed to work on Linux operating systems with a specific set of tools (like busybox) and doesn't work if the output is different. I still need to investigate this.

**Comment by mediaminister** [comment]
It was indeed a disk space issue, Chrome OS is downloading now.

**Comment by dagwieers** [comment]
BTW I may disable the ARMTests if it is not running on Travis because of the large download.

Also, I hope we can disable GitHub running alle checks on Travis twice (in fact since we test for 3 Python versions, we are downloading this 6x now).

@emilsvennesson Can you look into disabling one of the two Travis checks? They both work on the PR level, so doing it twice has no real advantage (except it takes longer for everything to finish).

**Comment by emilsvennesson** [comment]
@dagwieers Do you want to disable "Build pushed branches" or "Build pushed pull requests"?

https://docs.travis-ci.com/user/web-ui/#build-pushed-branches

**Comment by dagwieers** [comment]
@emilsvennesson I don't know :-) I don't understand the difference, it looks the same to me.

**Comment by emilsvennesson** [comment]
@dagwieers Haha, I'm also confused. I have disabled "Build pushed pull requests" now so let's see what happens. :-)

**Comment by dagwieers** [comment]
@mediaminister Maybe we ought to add Android as well, and we may want to test faking Krypton too.

**Comment by mediaminister** [comment]
Okay, but I didn't completed the current unit tests yet.
Now, I'm stuck on this:
```
  File "/home/test/script.module.inputstreamhelper/lib/inputstreamhelper.py", line 829, in _check_widevine
    if config.WIDEVINE_ARCH_MAP_X86[self._arch()] != wv_config['arch']:
TypeError: list indices must be integers, not unicode
```

**Comment by emilsvennesson** [comment]
@dagwieers Auto Cancellation maybe?

test

**Comment by dagwieers** [comment]
@mediaminister That looks like another Python 3 issue ? :-)

**Comment by dagwieers** [comment]
@emilsvennesson No, auto cancelation is quite useful. Can you try to disable this repository in Travis altogether? I think the *other* integration will keep on working.

**Comment by emilsvennesson** [comment]
@dagwieers That kills it altogether. :-/

**Comment by dagwieers** [comment]
@Can I try ?

**Comment by emilsvennesson** [comment]
@dagwieers Done.

**Comment by dagwieers** [comment]
Let me clarify, I think we have 2 kinds of integration enabled now. One that is linked to your account, and one that is linked to GitHub directly.

**Comment by dagwieers** [comment]
Seems to work fine: https://github.com/emilsvennesson/script.module.inputstreamhelper/pull/104

**Comment by dagwieers** [comment]
@emilsvennesson And Travis seems to be completely disabled now ? :-( Not sure why it worked for some window (i.e. #104)

**Comment by dagwieers** [comment]
> kay, but I didn't completed the current unit tests yet.
> Now, I'm stuck on this:
> 
> ```
>   File "/home/test/script.module.inputstreamhelper/lib/inputstreamhelper.py", line 829, in _check_widevine
>     if config.WIDEVINE_ARCH_MAP_X86[self._arch()] != wv_config['arch']:
> TypeError: list indices must be integers, not unicode
> ```

Ok, I found the cause for this. The code is using wv_config for 2 different types of data:
- On ARM it consists of recovery.conf in JSON format (a list of dictionaries)
- On non-ARM it is the widevine.conf from the ZIP file (a dictionary).

Now how come on x86 it gets a list in `_check_widevine()`? Because both are stored in the same exact filename, and when we are running tests, a previous ARM file may still be around. So this should be done better. We should store different content in different filenames, on ARM &rarr; recovery.conf.json.

**Pull request merged**
