### PR TITLE
Fix typo

### PR DESCRIPTION
**Pull request by Twilight0**

### CODE REVIEW

**Comment by dagwieers** [comment]
Thanks !

**Comment by ivankokan** [comment]
@dagwieers Consider updating https://github.com/emilsvennesson/script.module.inputstreamhelper/wiki/Integration as well.

**Comment by ivankokan** [comment]
> @dagwieers Consider updating https://github.com/emilsvennesson/script.module.inputstreamhelper/wiki/Integration as well.

Have you missed this?

**Comment by dagwieers** [comment]
Nope, haven't gotten around to it. I prefer if we open up to Wiki to outside collaboration.
@emilsvennesson ?

**Comment by emilsvennesson** [comment]
Sounds good to me! I've changed the settings now so that everyone can contribute to the wiki.

**Comment by ivankokan** [comment]
Done.

**Pull request merged**
