### PR TITLE
Convert subprocess output to unicode

### PR DESCRIPTION
**Pull request by mediaminister**
This should fix `UnicodeDecodeError` in https://github.com/emilsvennesson/script.module.inputstreamhelper/issues/210
@dagwieers @janhicken @GitUser4711  Please test.

### CODE REVIEW

**Comment by dagwieers** [comment]
@mediaminister I fixed a Python 3 issue.

**Comment by mediaminister** [comment]
Thanks for fixing, I overlooked that line. I hope to get some feedback so #210 can be closed.

**Comment by dagwieers** [comment]
@mediaminister I think we can merge this even if we don't get feedback ;-)

**Comment by mediaminister** [comment]
Sure.

**Pull request merged**
