### PR TITLE
Closes #333

### LINKED ISSUE #333: 'ascii' codec can't decode byte 0xc5 in position 29
I am running into the same error as in https://github.com/emilsvennesson/script.module.inputstreamhelper/issues/92

It happens during the extraction of widevine

I am on Kodi 18.6 Git_leia_pi4_18.6-Leia
Inputstream Helper 0.4.6
InputStream adaptive 2.4.4.1

```
2020-05-01 07:18:42.860 T:2573202288   ERROR: [plugin.video.netflix (1)] Traceback (most recent call last):
                                              File "/storage/.kodi/addons/plugin.video.netflix/resources/lib/run_addon.py", line 207, in run
                                                route([part for part in g.PATH.split('/') if part])
                                              File "/storage/.kodi/addons/plugin.video.netflix/resources/lib/run_addon.py", line 38, in lazy_login_wrapper
                                                return func(*args, **kwargs)
                                              File "/storage/.kodi/addons/plugin.video.netflix/resources/lib/run_addon.py", line 62, in route
                                                play(videoid=pathitems[1:])
                                              File "/storage/.kodi/addons/plugin.video.netflix/resources/lib/common/videoid.py", line 295, in wrapper
                                                return func(*args, **kwargs)
                                              File "/storage/.kodi/addons/plugin.video.netflix/resources/lib/common/logging.py", line 143, in timing_wrapper
                                                return func(*args, **kwargs)
                                              File "/storage/.kodi/addons/plugin.video.netflix/resources/lib/navigation/player.py", line 82, in play
                                                list_item = get_inputstream_listitem(videoid)
                                              File "/storage/.kodi/addons/plugin.video.netflix/resources/lib/navigation/player.py", line 163, in get_inputstream_listitem
                                                if not is_helper.check_inputstream():
                                              File "/storage/.kodi/addons/script.module.inputstreamhelper/lib/inputstreamhelper/__init__.py", line 407, in check_inputstream
                                                return self._check_drm()
                                              File "/storage/.kodi/addons/script.module.inputstreamhelper/lib/inputstreamhelper/__init__.py", line 362, in _check_drm
                                                return self.install_widevine()
                                              File "/storage/.kodi/addons/script.module.inputstreamhelper/lib/inputstreamhelper/__init__.py", line 33, in clean_before_after
                                                result = func(self, *args, **kwargs)
                                              File "/storage/.kodi/addons/script.module.inputstreamhelper/lib/inputstreamhelper/__init__.py", line 223, in install_widevine
                                                result = install_widevine_arm(backup_path())
                                              File "/storage/.kodi/addons/script.module.inputstreamhelper/lib/inputstreamhelper/widevine/arm.py", line 240, in install_widevine_arm
                                                extract_widevine_from_img(os.path.join(backup_path, arm_device['version']))
                                              File "/storage/.kodi/addons/script.module.inputstreamhelper/lib/inputstreamhelper/widevine/arm.py", line 253, in extract_widevine_from_img
                                                for root, _, files in os.walk(mnt_path()):
                                              File "/usr/lib/python2.7/os.py", line 296, in walk
                                              File "/usr/lib/python2.7/os.py", line 296, in walk
                                              File "/usr/lib/python2.7/os.py", line 296, in walk
                                              File "/usr/lib/python2.7/os.py", line 286, in walk
                                              File "/usr/lib/python2.7/posixpath.py", line 73, in join
                                            UnicodeDecodeError: 'ascii' codec can't decode byte 0xc5 in position 29: ordinal not in range(128)
```

### PR DESCRIPTION
**Pull request by BarmonHammer**
without str() I was getting an error "UnicodeDecodeError: 'ascii' codec can't decode byte 0xc5 in position 29: ordinal not in range(128)", adding str() fixes this error.

### CODE REVIEW

**Comment by mediaminister** [comment]
This doesn't fix the root cause of the problem.

**Comment by horstle** [comment]
I agree with @mediaminister . Especially since this could become an issue on some systems, see the failed check.

**Comment by BarmonHammer** [comment]
Sorry for the long  time to respond. Finals are today. 

@mediaminister Im a little confused by what you mean it doesn’t fix the cause of the problem. Passing Unicode to os.walk() can cause problems. Passing Unicode through str() then to os.walk() fixes it. 
Using str() has been used in 0.4.5 and most likely earlier versions, but for some reason was removed.
Is there a reason you want Unicode passed?

**Comment by dagwieers** [comment]
@BarmonHammer You fixed it for Python 3, and broke it for Python 2. That is why it was stated you did not fix it correctly.

**Comment by mediaminister** [comment]
>  Is there a reason you want Unicode passed?

Yes, this add-on needs to be compatible with both Kodi 18(python 2.7) and Kodi 19 (python 3.x) and to avoid future problems, unicode problems should be fixed in kodiutils.py.

**Pull request closed without merging**
