### PR TITLE
Prepare for v0.5.7 release

### PR DESCRIPTION
**Pull request by horstle**

### CODE REVIEW

**Comment by horstle** [comment]
Why is pylint compaining about that now?

**Comment by horstle** [comment]
Should we maybe remove `install_widevine_arm_legacy` this release?

**Comment by dtechsrv** [comment]
>Why is pylint compaining about that now?

Unfortunately, I don't understand the python language, but it's interesting that it gives an error to a line that hasn't been modified since the last couple of releases.

> Should we maybe remove `install_widevine_arm_legacy` this release?

Is this still some old method dating back to "pre-CromeOS" images?

**Comment by horstle** [comment]
> Is this still some old method dating back to "pre-CromeOS" images?

No, it's an old method to extract the widevine library from the ChromeOS image which required the image to be extracted completely.

I think I'll just quickly fix the pylint error. Removing that function would also mean removing multiple functions which are only required by that old method. I'd rather test that properly to make sure I didn't remove too much.

**Comment by horstle** [comment]
I'll release this tomorrow, if there are no objections @dagwieers, @mediaminister.

**Comment by dtechsrv** [comment]
All right, thanks a lot. ;-)

**Comment by mediaminister** [comment]
No objections. Looks good to me.

**Pull request merged**
